runtime: python311
app_engine_apis: true

includes:
  - env_variables.yaml

handlers:
  - url: /robots\.txt
    static_files: robots.txt
    upload: robots\.txt

  - url: /static
    static_dir: static

  - url: /.*
    script: auto
